Repository pm4-parkship/parkship, pull requests merged in 2023-04, with the labels that each got.

#18 Feat/pm4 7/show parking information
  frontend/src/components/parking-detail-modal/parking-detail-modal.tsx
Labels: size/xs

#29 feat: [PM4-11] add functionality to cancel a reservation
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationCanNotBeCanceledException.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationEntity.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationNotFoundException.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationState.java
  backend/src/test/java/ch/zhaw/parkship/AuthenticationControllerContextTest.java
  backend/src/test/java/ch/zhaw/parkship/UserServiceContextTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ReservationControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
Labels: size/xs

#30 feat [PM-4-8] Parkplatz reservieren backend
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/authentication/AuthenticationController.java
  backend/src/main/java/ch/zhaw/parkship/availability/AvailabilityService.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotRepository.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
  backend/src/main/java/ch/zhaw/parkship/user/UserEntity.java
  backend/src/main/java/ch/zhaw/parkship/user/UserService.java
  backend/src/test/java/ch/zhaw/parkship/AuthenticationControllerContextTest.java
  backend/src/test/java/ch/zhaw/parkship/StandaloneApplication.java
  backend/src/test/java/ch/zhaw/parkship/UserServiceContextTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotRepositoryTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ReservationControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/util/AbstractDataRollbackTest.java
  backend/src/test/java/ch/zhaw/parkship/util/AbstractDataTest.java
  backend/src/test/java/ch/zhaw/parkship/util/UserGenerator.java
  backend/src/test/java/ch/zhaw/parkship/util/generator/ParkingLotGenerator.java
  backend/src/test/java/ch/zhaw/parkship/util/generator/ReservationGenerator.java
Labels: size/m

#27 feat: [PM4-56] implement my-parkinglots
  backend/src/main/java/ch/zhaw/parkship/authentication/AuthenticationController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotRepository.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/user/UserEntity.java
  backend/src/main/java/ch/zhaw/parkship/user/UserService.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
Labels: size/xs

#31 Feat/pm4 58/show own parkingspaces
  frontend/pages/test/index.tsx
  frontend/src/components/parking-detail-modal/parking-detail-modal.tsx
  frontend/src/components/parking-list-empty-item/parking-list-empty-item.tsx
  frontend/src/components/parking-list-item/parking-list-item.tsx
  frontend/src/components/parking-list/parking-list.tsx
  frontend/src/models/parking-lot/parking-lot.model.ts
Labels: size/xs

#32 feat: [PM4-xx] refactor login and activate protected routes
  frontend/middleware.ts
  frontend/package-lock.json
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/api/login.ts
  frontend/pages/api/user.ts
  frontend/pages/index.tsx
  frontend/pages/login.tsx
  frontend/pages/my-reservation/index.tsx
  frontend/pages/profile/index.tsx
  frontend/pages/search/index.tsx
  frontend/src/auth/form.tsx
  frontend/src/auth/use-user.ts
  frontend/src/components/layout/layout.tsx
  frontend/src/components/navbar/navbar.tsx
  frontend/src/fetch-json/fetch-json.ts
  frontend/tsconfig.json
Labels: size/m

#33 feat: [PM4-55] refactored table component. search and reservationlist connected
  frontend/pages/login.tsx
  frontend/pages/my-reservation/index.tsx
  frontend/pages/search/index.tsx
  frontend/src/auth/use-user.ts
  frontend/src/components/layout/layout.tsx
  frontend/src/components/loading-buffer/loading-buffer.tsx
  frontend/src/components/my-reservation/reservation-table.tsx
  frontend/src/components/search-parking-lot/search-parking-lot-table.tsx
  frontend/src/components/table/table-component.tsx
  frontend/src/components/table/table-row.tsx
  frontend/src/data/parkinglots.tsx
  frontend/src/data/reservations.tsx
  frontend/src/models/reservation/reservation.model.ts
  frontend/src/models/search/search-result.model.ts
Labels: size/s

#34 Release sprint 3
  backend/readme.md
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/StandaloneApplication.java
  backend/src/main/java/ch/zhaw/parkship/authentication/AuthenticationController.java
  backend/src/main/java/ch/zhaw/parkship/availability/AvailabilityService.java
  backend/src/main/java/ch/zhaw/parkship/configuration/ApplicationConfiguration.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotRepository.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
  backend/src/main/java/ch/zhaw/parkship/user/UserEntity.java
  backend/src/main/java/ch/zhaw/parkship/user/UserService.java
  backend/src/test/java/ch/zhaw/parkship/AuthenticationControllerContextTest.java
  backend/src/test/java/ch/zhaw/parkship/UserServiceContextTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotRepositoryTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ReservationControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/util/AbstractDataRollbackTest.java
  backend/src/test/java/ch/zhaw/parkship/util/AbstractDataTest.java
  backend/src/test/java/ch/zhaw/parkship/util/UserGenerator.java
  backend/src/test/java/ch/zhaw/parkship/util/generator/ParkingLotGenerator.java
  backend/src/test/java/ch/zhaw/parkship/util/generator/ReservationGenerator.java
  frontend/middleware.ts
  frontend/package-lock.json
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/api/login.ts
  frontend/pages/api/user.ts
  frontend/pages/index.tsx
  frontend/pages/login.tsx
  frontend/pages/my-reservation/index.tsx
  frontend/pages/profile/index.tsx
  frontend/pages/search/index.tsx
  frontend/pages/test/index.tsx
  frontend/src/auth/form.tsx
  frontend/src/auth/use-user.ts
  frontend/src/components/layout/layout.tsx
  frontend/src/components/loading-buffer/loading-buffer.tsx
  frontend/src/components/my-reservation/reservation-table.tsx
  frontend/src/components/navbar/navbar.tsx
  frontend/src/components/parking-detail-modal/parking-detail-modal.tsx
  frontend/src/components/parking-list-empty-item/parking-list-empty-item.tsx
  frontend/src/components/parking-list-item/parking-list-item.tsx
  frontend/src/components/parking-list/parking-list.tsx
  frontend/src/components/search-parking-lot/search-parking-lot-table.tsx
  frontend/src/components/table/table-component.tsx
  frontend/src/components/table/table-row.tsx
  frontend/src/data/parkinglots.tsx
  frontend/src/data/reservations.tsx
  frontend/src/fetch-json/fetch-json.ts
  frontend/src/models/parking-lot/parking-lot.model.ts
  frontend/src/models/reservation/reservation.model.ts
  frontend/src/models/search/search-result.model.ts
  frontend/tsconfig.json
Labels: size/l

#38 fix [NO-TICKET] init Data for production
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
Labels: size/xs

#39 feat: [PM4-75] meeting notes stuff
  frontend/pages/admin/index.tsx
  frontend/pages/login.tsx
  frontend/pages/search/index.tsx
  frontend/src/components/layout/layout.tsx
  frontend/src/components/navbar/navbar.tsx
  frontend/src/components/table/table-row.tsx
  frontend/src/data/reservations.tsx
  frontend/src/models/user/user.model.ts
Labels: size/xs

#36 feat: [PM4-76] add custom error handling
  backend/src/main/java/ch/zhaw/parkship/errorhandling/ApiError.java
  backend/src/main/java/ch/zhaw/parkship/errorhandling/ApiSubError.java
  backend/src/main/java/ch/zhaw/parkship/errorhandling/ApiValidationError.java
  backend/src/main/java/ch/zhaw/parkship/errorhandling/BaseException.java
  backend/src/main/java/ch/zhaw/parkship/errorhandling/GlobalExceptionControllerAdvice.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationCanNotBeCanceledException.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationNotFoundException.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
  backend/src/main/java/ch/zhaw/parkship/reservation/exceptions/ReservationCanNotBeCanceledException.java
  backend/src/main/java/ch/zhaw/parkship/reservation/exceptions/ReservationNotFoundException.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
Labels: size/xs

#37 feat [PM4-2] made various little changes in the user login page
  frontend/pages/login.tsx
Labels: size/xs

#42 feat: [PM4-73] admin parkplatzliste UI
  frontend/middleware.ts
  frontend/pages/admin/parking-lots/index.tsx
  frontend/pages/admin/users/index.tsx
  frontend/pages/api/logout.ts
  frontend/pages/api/user.ts
  frontend/pages/login.tsx
  frontend/pages/logout.tsx
  frontend/pages/my-reservation/index.tsx
  frontend/pages/search/index.tsx
  frontend/pages/test/index.tsx
  frontend/src/components/layout/layout.tsx
  frontend/src/components/my-reservation/reservation-state-icon.tsx
  frontend/src/components/my-reservation/reservation-table.tsx
  frontend/src/components/navbar/drawer/drawer-admin.tsx
  frontend/src/components/navbar/drawer/drawer-user.tsx
  frontend/src/components/navbar/navbar-admin.tsx
  frontend/src/components/navbar/navbar-user.tsx
  frontend/src/components/parking-detail-modal/parking-detail-modal.tsx
  frontend/src/components/parking-list/parking-list-empty-item.tsx
  frontend/src/components/parking-list/parking-list-item.tsx
  frontend/src/components/parking-list/parking-list.tsx
  frontend/src/components/parking-lots-list/parking-lot-state-toggle-button.tsx
  frontend/src/components/parking-lots-list/parking-lots-filter.tsx
  frontend/src/components/parking-lots-list/parking-lots-table.tsx
  frontend/src/components/search-parking-lot/search-parking-lot-table.tsx
  frontend/src/components/table/table-component.tsx
  frontend/src/components/table/table-row.tsx
  frontend/src/data/parkinglots.tsx
  frontend/src/mock-data/parking-lot-dummy.tsx
  frontend/src/mock-data/reservations-dummy.tsx
  frontend/src/mock-data/search-dummy.tsx
  frontend/src/models/parking-lot/parking-lot.model.ts
  frontend/src/models/search/search-result.model.ts
  frontend/src/models/user/user.model.ts
Labels: size/l

#41 feat [PM4-65]: Implement endpoint to retrieve all users for ADMIN users
  backend/src/main/java/ch/zhaw/parkship/user/UserController.java
  backend/src/main/java/ch/zhaw/parkship/user/UserService.java
  backend/src/test/java/ch/zhaw/parkship/controllers/UserControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/UserServiceTest.java
Labels: size/xs

#40 Feat/pm4 70/admin parkinglot list
  backend/pom.xml
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/common/PaginatedResponse.java
  backend/src/main/java/ch/zhaw/parkship/configuration/ApplicationConfiguration.java
  backend/src/main/java/ch/zhaw/parkship/errorhandling/GlobalExceptionControllerAdvice.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/user/UserService.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerAdminTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
Labels: size/xs
