Repository pm4-parkship/parkship, pull requests merged in 2023-05, with the labels that each got.

#44 feat: [PM4-75] improve login handle
  frontend/middleware.ts
  frontend/pages/api/login.ts
  frontend/pages/api/user.ts
  frontend/pages/login.tsx
  frontend/src/auth/use-user.ts
Labels: size/xs

#47 feat: [PM4-74] update ParkingLotState backend enpoint
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotDto.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotEntity.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotState.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/util/AbstractDataTest.java
  backend/src/test/java/ch/zhaw/parkship/util/generator/ParkingLotGenerator.java
Labels: size/xs

#48 feat: [PM4-16] parkplatz freigeben und sperren UI
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotRepository.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotState.java
  frontend/pages/admin/parking-lots/index.tsx
  frontend/src/components/parking-lots-list/parking-lot-state-toggle-button.tsx
  frontend/src/models/parking-lot/parking-lot.model.ts
Labels: size/xs

#46 Feat/pm4 53/confirm modal
  frontend/pages/search/index.tsx
  frontend/src/components/parking-detail-modal/parking-detail-modal.tsx
  frontend/src/components/parking-reservation-confirmation-modal/parking-reservation-confirmation-modal.tsx
Labels: size/xs

#53 feat: [PM4-42] suche mit tags erweitert
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/tag/TagDto.java
  backend/src/main/java/ch/zhaw/parkship/tag/TagEntity.java
  backend/src/main/java/ch/zhaw/parkship/tag/TagRepository.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
  frontend/pages/search/index.tsx
Labels: size/xs

#52 feat [PM4-61] reservations endpoint to ParkingLotController
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationHistoryDto.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
Labels: size/xs

#56 fix [PM4-61] : broken testing
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
Labels: size/xs

#51 Feat/pm4 10/modify reservation
  frontend/pages/admin/parking-lots/index.tsx
  frontend/pages/login.tsx
  frontend/pages/my-reservation/index.tsx
  frontend/pages/search/index.tsx
  frontend/src/components/layout/layout.tsx
  frontend/src/components/my-reservation/reservation-cancel-cell.tsx
  frontend/src/components/my-reservation/reservation-filter.tsx
  frontend/src/components/my-reservation/reservation-state-icon.tsx
  frontend/src/components/my-reservation/reservation-table.tsx
  frontend/src/components/parking-detail-modal/parking-detail-modal.tsx
  frontend/src/components/parking-lots-list/parking-lots-filter.tsx
  frontend/src/components/parking-lots-list/parking-lots-table.tsx
  frontend/src/components/parking-reservation-confirmation-modal/parking-reservation-confirmation-modal.tsx
  frontend/src/components/reservation/cancel-reservation-modal.tsx
  frontend/src/components/reservation/confirmation-modal.tsx
  frontend/src/components/reservation/create-reservation-modal.tsx
  frontend/src/components/reservation/modify-reservation-modal.tsx
  frontend/src/components/table/table-component.tsx
  frontend/src/components/table/table-row.tsx
  frontend/src/models/parking-lot/parking-lot.model.ts
  frontend/src/models/reservation/reservation.model.ts
  frontend/styles/globals.css
  frontend/styles/theme/theme.ts
Labels: size/l

#43 Feat/pm4 9/display reservations
  backend/readme.md
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationRepository.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ReservationControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
Labels: size/xs

#60 [PM4-9] added implementation for showing user reservations
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationController.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationRepository.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationService.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ReservationControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
Labels: size/xs

#54 feat: [PM4-52] [PM4-71] parkplatz suche erweitert und parkplatz anlegen
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/offer/OfferController.java
  backend/src/main/java/ch/zhaw/parkship/offer/OfferDto.java
  backend/src/main/java/ch/zhaw/parkship/offer/OfferEntity.java
  backend/src/main/java/ch/zhaw/parkship/offer/OfferRepository.java
  backend/src/main/java/ch/zhaw/parkship/offer/OfferService.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotDto.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotEntity.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotRepository.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationEntity.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationRepository.java
  backend/src/test/java/ch/zhaw/parkship/controllers/OfferControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerAdminTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotRepositoryTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ReservationControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/util/AbstractDataTest.java
Labels: size/l

#57 feat [PM4-64] created the user list ui for the admin
  frontend/pages/admin/users/index.tsx
  frontend/src/components/my-parking-lot-reservations/my-parking-lot-reservations.tsx
  frontend/src/components/my-reservation/reservation-table.tsx
  frontend/src/components/parking-lots-list/parking-lots-table.tsx
  frontend/src/components/search-parking-lot/search-parking-lot-table.tsx
  frontend/src/components/table/table-component.tsx
  frontend/src/components/user-list/user-filter.tsx
  frontend/src/components/user-list/user-state-toggle-button.tsx
  frontend/src/components/user-list/users-table.tsx
  frontend/src/models/user/user.model.ts
Labels: size/s

#64 fix: [PM4-89] added clipboard (copyfunction)
  frontend/src/components/user-administration/user-administration-modal/show-password-modal.tsx
Labels: bug, size/xs

#63 changed from ownerID to ownerdto
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotDto.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
Labels: size/xs

#66 [pm4-97] removed email from dto
  backend/src/main/java/ch/zhaw/parkship/user/ParkshipUserDetails.java
  backend/src/main/java/ch/zhaw/parkship/user/UserController.java
  backend/src/main/java/ch/zhaw/parkship/user/UserDto.java
  backend/src/main/java/ch/zhaw/parkship/user/UserEntity.java
  backend/src/main/java/ch/zhaw/parkship/user/UserRepository.java
  backend/src/main/java/ch/zhaw/parkship/user/UserService.java
  backend/src/test/java/ch/zhaw/parkship/AuthenticationControllerContextTest.java
  backend/src/test/java/ch/zhaw/parkship/UserServiceContextTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ReservationControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/UserControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/services/UserServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/util/UserGenerator.java
Labels: size/xs

#68 feat: [PM4-93] perimeter search
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotRepository.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/PerimeterSearchDto.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotRepositoryTest.java
Labels: size/xs

#69 Feat/pm4 14/create new parking v2
  .github/workflows/build-push-deploy.yaml
  .github/workflows/ci-backend.yaml
  .github/workflows/ci-frontend.yaml
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  backend/src/main/java/ch/zhaw/parkship/offer/OfferController.java
  backend/src/main/java/ch/zhaw/parkship/offer/OfferDto.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotController.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotEntity.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/ParkingLotService.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/dtos/ParkingLotCreateDto.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/dtos/ParkingLotDto.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/dtos/ParkingLotSearchDto.java
  backend/src/main/java/ch/zhaw/parkship/parkinglot/dtos/PerimeterSearchDto.java
  backend/src/main/java/ch/zhaw/parkship/reservation/ReservationDto.java
  backend/src/main/java/ch/zhaw/parkship/tag/TagDto.java
  backend/src/main/java/ch/zhaw/parkship/tag/TagRepository.java
  backend/src/test/java/ch/zhaw/parkship/controllers/OfferControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerAdminTest.java
  backend/src/test/java/ch/zhaw/parkship/controllers/ParkingLotControllerTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ParkingLotServiceTest.java
  backend/src/test/java/ch/zhaw/parkship/services/ReservationServiceTest.java
  frontend/pages/admin/parking-lots/index.tsx
  frontend/pages/admin/users/index.tsx
  frontend/pages/create-parking-lot/index.tsx
  frontend/pages/login.tsx
  frontend/pages/my-parking-lot/index.tsx
  frontend/pages/my-reservation/index.tsx
  frontend/pages/search/index.tsx
  frontend/src/components/create-parking-modal/bookings/bookings.tsx
  frontend/src/components/create-parking-modal/create-parking-modal.tsx
  frontend/src/components/my-parking-lot-reservations/my-parking-lot-reservations.tsx
  frontend/src/components/my-reservation/reservation-cancel-cell.tsx
  frontend/src/components/my-reservation/reservation-table.tsx
  frontend/src/components/parking-list-empty-item/parking-list-empty-item.tsx
  frontend/src/components/parking-list-item/parking-list-item.tsx
  frontend/src/components/parking-list/my-parking-lot-list.tsx
  frontend/src/components/parking-list/parking-list-empty-item.tsx
  frontend/src/components/parking-list/parking-list-item.tsx
  frontend/src/components/parking-list/parking-list.tsx
  frontend/src/components/parking-lots-list/parking-lots-filter.tsx
  frontend/src/components/parking-lots-list/parking-lots-table.tsx
  frontend/src/components/reservation/confirmation-modal.tsx
  frontend/src/components/search-bar/search-bar.tsx
  frontend/src/components/search-bar/tag-menu.tsx
  frontend/src/components/search-parking-lot/search-parking-lot-table.tsx
  frontend/src/components/table/table-component.tsx
  frontend/src/components/table/table-header.tsx
  frontend/src/components/user-list/users-table.tsx
  frontend/src/models/parking-lot/parking-lot.model.ts
Labels: size/l

#70 Feat/pm4 91/show name correctly
  backend/src/main/java/ch/zhaw/parkship/authentication/AuthenticationController.java
  frontend/pages/api/login.ts
  frontend/pages/api/logout.ts
  frontend/pages/api/user.ts
  frontend/pages/login.tsx
  frontend/src/components/layout/layout.tsx
  frontend/src/components/navbar/drawer/drawer-admin.tsx
  frontend/src/components/navbar/drawer/drawer-user.tsx
  frontend/src/components/navbar/navbar-admin.tsx
  frontend/src/components/navbar/navbar-user.tsx
Labels: size/xs

#72 fix: [PM4-XX] http 204
  backend/src/main/java/ch/zhaw/parkship/ParkshipApplication.java
  frontend/pages/api/api-client.ts
  frontend/pages/my-parking-lot/index.tsx
  frontend/pages/my-reservation/index.tsx
  frontend/src/components/my-parking-lot-reservations/parking-lots-filter.tsx
  frontend/src/components/my-reservation/reservation-table.tsx
  frontend/src/components/parking-list/my-parking-lot-list.tsx
Labels: size/xs
